# Generated by Django 4.2.7 on 2023-11-23 13:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], max_length=6)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('cat_spec_properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-creation'],
            },
            managers=[
                ('all_listings', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(default='Poland', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'listing locations',
            },
            managers=[
                ('locations', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('prop1_name', models.CharField(blank=True, max_length=30)),
                ('prop2_name', models.CharField(blank=True, max_length=30)),
                ('prop3_name', models.CharField(blank=True, max_length=30)),
                ('prop4_name', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'main categories',
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('url', models.CharField(default='SETDEFAULTIMGURL.COM', max_length=200)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.maincategory')),
            ],
            options={
                'verbose_name_plural': 'listing categories',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.listingcategory'),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='listings.listinglocation'),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
