# Generated by Django 4.2.7 on 2023-11-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='url',
            field=models.CharField(default='SETDEFAULTIMGURL.COM', max_length=200),
        ),
    ]
