# Generated by Django 4.2.7 on 2023-11-15 14:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingimage_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingcategory',
            options={'verbose_name_plural': 'listing categories'},
        ),
        migrations.AlterModelOptions(
            name='listinglocation',
            options={'verbose_name_plural': 'listing locations'},
        ),
        migrations.AlterModelManagers(
            name='listing',
            managers=[
                ('all_listings', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='listinglocation',
            managers=[
                ('locations', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='listinglocation',
            name='apt_number',
        ),
        migrations.RemoveField(
            model_name='listinglocation',
            name='number',
        ),
        migrations.RemoveField(
            model_name='listinglocation',
            name='street',
        ),
        migrations.AddField(
            model_name='listinglocation',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listinglocation',
            name='country',
            field=models.CharField(default='Poland', max_length=50),
        ),
    ]
