# Generated by Django 4.2.7 on 2023-11-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_cat_spec_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='icon',
            field=models.CharField(default='SETDEFAULTIMGURL.COM', max_length=200),
        ),
    ]
