# Generated by Django 5.0 on 2024-01-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_maincategory_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cat_spec_properties',
        ),
        migrations.AddField(
            model_name='listing',
            name='cat_num_prop_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='cat_num_prop_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='cat_text_prop_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='cat_text_prop_2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
