# Generated by Django 5.0 on 2024-01-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_cat_spec_properties_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='cat_num_prop_1',
            new_name='cat_num_prop_3',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='cat_num_prop_2',
            new_name='cat_num_prop_4',
        ),
    ]
